version: '3.9'

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: coordinates
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    image: neginmalekzadeh/coordinate-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres